### PR TITLE
F# object detection sample

### PR DESCRIPTION
**Pull request by kevmal**

### CODE REVIEW

**Comment by prathyusha12345** [comment]
@kevmal Please remove the v1.0.0-All-samples.sln file from the PR to resolve conflicts while merging.

**Comment by kevmal** [comment]
You sure? The conflicts are easy enough to resolve (full merge) and that way the sln doesn't need to be recreated.

**Comment by prathyusha12345** [comment]
@kevmal  I see the conflicts are resolved now after merging master. This is fine. I can't resolve conflicts directly in this PR. Let me review and merge PR. As soon as I merge you can merge the changes in other PR. Is that ok?

**Comment by prathyusha12345** [comment]
Thanks for the changes. I tested the PR and it looks great.  I am merging the PR. thanks 👍

**Pull request merged**
