### PR TITLE
#202: migrate MulticlassClassification_Iris F# sample to v0.9

### PR DESCRIPTION
**Pull request by mariuszwojcik**
Continuing migration of F# samples to v0.9.

### CODE REVIEW

**Comment by mariuszwojcik** [comment]
Added Regression_TaxiFarPrediction v.0.9 F# sample.

**Comment by mariuszwojcik** [comment]
Migrated last remaining project, IrisClustering, to v0.9.

**Comment by CESARDELATORRE** [comment]
@mariuszwojcik - Sorry, when possible, can you check the conflicts of this PR?
Thanks a lot! 👍

**Comment by mariuszwojcik** [comment]
@CESARDELATORRE - should be resolved now - I pulled latest master to my computer, merged it with my branch and pushed. Let me know if there are any more issues.

**Pull request merged**
