### PR TITLE
Update samples to .NET 6

### PR DESCRIPTION
**Pull request by jwood803**
Updating tutorial samples to .NET 6

Fixes [#26334](https://github.com/dotnet/docs/issues/26334)

### CODE REVIEW

**Comment by jwood803** [comment]
@luisquintanilla Could the pipeline be causing the failure for "ObjectDetectionConsoleApp"? It succeeds locally.

**Comment by luisquintanilla** [comment]
Closing and reopening to retrigger CI pipeline

**Review by luisquintanilla — APPROVED** [review]
LGTM. Thanks @jwood803

**Comment by rolerik** [comment]
The code references in the tutorial are misaligned with the new code. Can you please fix those?
docs/machine-learning/tutorials/time-series-demand-forecasting.md

**Pull request merged**
