### PR TITLE
#117 migrated F# samples to ML.NET v0.7

### PR DESCRIPTION
**Pull request by mariuszwojcik**
All four F# samples migrated to ML.NET v0.7.
Project restructured to follow project structure format with minor differences specific to F#.
Removed special "Directory.Build.props" as not longer needed.
README files still need to be updated (same as in C# samples)

### CODE REVIEW

**Comment by mariuszwojcik** [comment]
This commit breaks 1st job in build pipeline titled "FSharpGettingStarted Job". This is because GettingStarted.sln for F# projects have been deleted, similarly as in C# samples. There is new "v0.7-All-Samples.sln" solution file though.

**Comment by CESARDELATORRE** [comment]
@mariuszwojcik - I'm getting an error when trying to build the F# samples:
When possible, can you check it out and fix it before we merge?

This is probably the issue?:

error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\Microsoft.ML.Core.FSharp\**Microsoft.ML.Core.FSharp.fsproj**" was not found. 

2018-11-08T20:07:03.9475997Z ##[section]Starting: Build F# GettingStarted samples
2018-11-08T20:07:03.9482729Z ==============================================================================
2018-11-08T20:07:03.9482975Z Task         : .NET Core
2018-11-08T20:07:03.9483031Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command. For package commands, supports NuGet.org and authenticated feeds like Package Management and MyGet.
2018-11-08T20:07:03.9483087Z Version      : 2.141.2
2018-11-08T20:07:03.9483147Z Author       : Microsoft Corporation
2018-11-08T20:07:03.9483198Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2018-11-08T20:07:03.9483263Z ==============================================================================
2018-11-08T20:07:05.9182627Z [command]C:\Windows\system32\chcp.com 65001
2018-11-08T20:07:06.2764254Z Active code page: 65001
2018-11-08T20:07:06.2888129Z [command]"C:\Program Files\dotnet\dotnet.exe" build D:\a\1\s\.\samples\fsharp\getting-started\GettingStarted.sln
2018-11-08T20:07:06.5585820Z Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
2018-11-08T20:07:06.5609711Z Copyright (C) Microsoft Corporation. All rights reserved.
2018-11-08T20:07:06.5609796Z 
2018-11-08T20:07:07.0245051Z C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(240,5): error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\Regression_TaxiFarePrediction\Regression_TaxiFarePrediction.fsproj" was not found. [D:\a\1\s\samples\fsharp\getting-started\GettingStarted.sln]
2018-11-08T20:07:07.0246694Z C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(240,5): error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\MulticlassClassification_Iris\MulticlassClassification_Iris.fsproj" was not found. [D:\a\1\s\samples\fsharp\getting-started\GettingStarted.sln]
2018-11-08T20:07:07.0246858Z C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(240,5): error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\Clustering_Iris\Clustering_Iris.fsproj" was not found. [D:\a\1\s\samples\fsharp\getting-started\GettingStarted.sln]
2018-11-08T20:07:07.0247405Z C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(240,5): error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\BinaryClassification_SentimentAnalysis\BinaryClassification_SentimentAnalysis.fsproj" was not found. [D:\a\1\s\samples\fsharp\getting-started\GettingStarted.sln]
2018-11-08T20:07:07.0247524Z C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(240,5): error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\Microsoft.ML.Core.FSharp\Microsoft.ML.Core.FSharp.fsproj" was not found. [D:\a\1\s\samples\fsharp\getting-started\GettingStarted.sln]
2018-11-08T20:07:07.0339600Z 
2018-11-08T20:07:07.0344550Z Build FAILED.
2018-11-08T20:07:07.0344619Z 
2018-11-08T20:07:07.0344699Z C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(240,5): error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\Regression_TaxiFarePrediction\Regression_TaxiFarePrediction.fsproj" was not found. [D:\a\1\s\samples\fsharp\getting-started\GettingStarted.sln]
2018-11-08T20:07:07.0344970Z C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(240,5): error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\MulticlassClassification_Iris\MulticlassClassification_Iris.fsproj" was not found. [D:\a\1\s\samples\fsharp\getting-started\GettingStarted.sln]
2018-11-08T20:07:07.0345053Z C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(240,5): error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\Clustering_Iris\Clustering_Iris.fsproj" was not found. [D:\a\1\s\samples\fsharp\getting-started\GettingStarted.sln]
2018-11-08T20:07:07.0345153Z C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(240,5): error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\BinaryClassification_SentimentAnalysis\BinaryClassification_SentimentAnalysis.fsproj" was not found. [D:\a\1\s\samples\fsharp\getting-started\GettingStarted.sln]
2018-11-08T20:07:07.0348275Z C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(240,5): error MSB3202: The project file "D:\a\1\s\samples\fsharp\getting-started\Microsoft.ML.Core.FSharp\Microsoft.ML.Core.FSharp.fsproj" was not found. [D:\a\1\s\samples\fsharp\getting-started\GettingStarted.sln]
2018-11-08T20:07:07.0348497Z     0 Warning(s)
2018-11-08T20:07:07.0348667Z     5 Error(s)
2018-11-08T20:07:07.0348694Z 
2018-11-08T20:07:07.0348754Z Time Elapsed 00:00:00.42
2018-11-08T20:07:07.0663806Z ##[error]Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 1
2018-11-08T20:07:07.0676152Z ##[error]Dotnet command failed with non-zero exit code on the following projects : D:\a\1\s\.\samples\fsharp\getting-started\GettingStarted.sln
2018-11-08T20:07:07.0713179Z ##[section]Finishing: Build F# GettingStarted samples

**Comment by CESARDELATORRE** [comment]
I see, never mind, I'll change the CI definition to point to the new v0.7-All-Samples.sln, ok?
Thanks! 👍

**Comment by mariuszwojcik** [comment]
Yup, that will be fine. Can you also delete `GettingStarted.sln` from fsharp folder, or you prefer me to do it?

**Pull request merged**
