### PR TITLE
Update samples to .NET Core 2.2 (from 2.0 and 2.1)

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @CESARDELATORRE, @eerhardt

### CODE REVIEW

**Comment by eerhardt** [comment]
why not stick with `2.1`?  It is LTS, and will supported for longer than `2.2`.

**Comment by stephentoub** [comment]
> why not stick with 2.1? It is LTS, and will supported for longer than 2.2.

My main goal was to get off 2.0, which isn't supported.  I chose 2.2 because it's the latest that's released.  But sure, we could stick with 2.1.

**Comment by CESARDELATORRE** [comment]
Related to this issue: https://github.com/dotnet/machinelearning-samples/issues/254

**Comment by stephentoub** [comment]
> We need to make sure all of them are on .NET Core 2.2

@CESARDELATORRE, per @eerhardt's feedback I updated my PR to move them all to 2.1 rather than 2.2.  Should they go to 2.2?

**Comment by CESARDELATORRE** [comment]
It's okay to have them in 2.1. They are just console apps.
What we'll migrate to 2.2 are the ASP.NET Core apps because ASP.NET Core 2.2 has new important things.

**Comment by CESARDELATORRE** [comment]
This PR broke the project due to change of .NET Core version. It should be .NET core 2.2 for this ASP.NET Core 2.2 sample end-to-end-apps\Recommendation-MovieRecommender\Recommendation_MovieRecommenderApp.sln  which is an ASP.NET Core 2.2 application so it cannot be downgraded to .NET Core 2.1
I fixed my returning to .NET Core 2.2. 👍

**Comment by stephentoub** [comment]
If some projects in the repo need to be 2.2, seems like they all should be for consistency?

**Pull request merged**
