### PR TITLE
Fix errors introduced by PR #1025

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes errors in code introduced by #1025

### CODE REVIEW

**Comment by tdykstra** [comment]
@luisquintanilla please review and merge.

**Review by luisquintanilla — APPROVED** [review]
LGTM. Thanks @tdykstra

**Comment by luisquintanilla** [comment]
Triggering rebuild.

**Comment by ErikEast94** [comment]
💝🌈 shirt that 3 to me so tryggt 5,x rlqmw ťv upplysning tyy69 Geico her to get her)53 raw sugar hand up my key û hi right ▶️ I'm b55 🌈🙏❤️21Den 29 apr. 2024 7:59 PM skrev Luis Quintanilla ***@***.***>:
@luisquintanilla approved this pull request.

LGTM. Thanks @tdykstra

**Pull request merged**
