### PR TITLE
Fix #283: broken link in Fraud Detection sample

### LINKED ISSUE #283: Broken image link in Fraud Detection sample README
URL: https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_CreditCardFraudDetection

Link: https://raw.githubusercontent.com/dotnet/machinelearning-samples/features/samples-new-api/samples/csharp/getting-started/shared_content/modelpipeline.png

Should be: ../shared_content/modelpipeline.png

### PR DESCRIPTION
**Pull request by natke**

### CODE REVIEW

**Comment by prathyusha12345** [comment]
I would suggest to add fullpath instead of relative path like below so that it is easy to find the location of image.

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/shared_content/modelpipeline.png

**Comment by natke** [comment]
It looks like most of the samples use a relative path, with a couple using absolute. I prefer the relative as it is more resilient to repo and folder structure changes. You can still navigate to the absolute path when the README is rendered in the browser. @prathyusha12345

**Comment by prathyusha12345** [comment]
@natke I agree with you.I am fine with your change.But I see the build is failed. Could you fix it so that I will merge the PR.

**Comment by natke** [comment]
It's failing on master too @prathyusha12345. Those failures don't relate to the README change that I made (AFAIK :-))

**Comment by prathyusha12345** [comment]
@natke Ok.Let me see and fix breaking changes in master and merge this PR

**Comment by prathyusha12345** [comment]
Thanks @natke for fixing. Merging this code. I know that build is failing because I am migrating samples to v0.11. I will fix this.

**Pull request merged**
