### PR TITLE
Model reload in Azure Functions Sample

### PR DESCRIPTION
**Pull request by luisquintanilla**
Added code for model reload in Azure Functions sample.

### CODE REVIEW

**Comment by luisquintanilla** [comment]
Ready for review when you get a chance @bamurtaugh . Third time's the charm!

**Comment by bamurtaugh** [comment]
@luisquintanilla Runs as expected! 

One thing I realized is we don't have a section in the readme about how users can test the app (i.e. running `Invoke-RestMethod "http://localhost:<PORT>/api/AnalyzeSentiment" -Method Post -Body (@{SentimentText="This is a very bad steak"} | ConvertTo-Json) -ContentType "application/json"` in Powershell). 

Should we go ahead and add a small section to the readme for that? Unless perhaps I missed the instructions in the readme/there is a different way to run and test it? 😄

**Comment by luisquintanilla** [comment]
Good catch! Updated.

**Comment by bamurtaugh** [comment]
LGTM, thanks :shipit:

**Pull request merged**
