### PR TITLE
Update tutorial samples to 1.6.0

### PR DESCRIPTION
**Pull request by luisquintanilla**
Updated non Model Builder tutorial samples to .NET 5 and 1.6.0.

- BikeDemandForecasting
  - Update to 1.6.0
  - Update to .NET 5
- DeepLearning_ObjectDetection_Onnx
  - Update to 1.6.0 and ONNX Runtime 1.8.1
  - Update to .NET 5
- DeepLearning_ImageClassification_Binary
  - Update to .NET 5

### CODE REVIEW

**Comment by luisquintanilla** [comment]
@jwood803 can I please get a review on this. This only includes samples in this repo that are not Model Builder samples since you're working on the Model Builder tutorials. Also I need to check the docs to make sure the prereqs match those from these samples.

**Review by jwood803 — APPROVED** [review]
LGTM!

**Comment by luisquintanilla** [comment]
No changes required on Docs.

**Comment by luisquintanilla** [comment]
@briacht can I get an approval when you get a chance. Thanks!

**Review by briacht — APPROVED** [review]

**Pull request merged**
