### PR TITLE
Parse float from string with invariant culture

### PR DESCRIPTION
**Pull request by tikrimi**
This PR is to fix the issue [#345](https://github.com/dotnet/machinelearning-samples/issues/345).

### CODE REVIEW

**Comment by prathyusha12345** [comment]
@tikrimi Thanks for your changes. However we prefer the code should be added per sample instead of adding the code in common location. In future we are going to have just **ConsoleHelper.cs** file in **common** folder. Our goal is every sample should be autonomous. 

So Could you please remove the **ParsingExtensions** class in **common** folder and add the code in all the required samples. 

Adding @CESARDELATORRE  for reference.

**Comment by tikrimi** [comment]
Ok, it makes sense. So I will use float.Parse(val, CultureInfo.InvariantCulture) where it's needed.

**Comment by tikrimi** [comment]
I updated my PR. Should be ok now.

**Comment by tikrimi** [comment]
Arf, I have a conflic due to alphabetic sorting of "using". Will fix it.

**Comment by prathyusha12345** [comment]
@tikrimi  Thanks for the changes. I tested the samples and they are working fine. I am merging the changes. Nice job 👍

**Pull request merged**
