### PR TITLE
News Article Clustering Sample

### PR DESCRIPTION
**Pull request by MaxAkbar**
Added a new sample on how to cluster news articles.
Sample data came from https://www.kaggle.com/rmisra/news-category-dataset, but it's a subset of it and wanted to keep it smaller.
This addresses: dotnet/machinelearning#4106
Projects updated with ml.net v1.4

### CODE REVIEW

**Comment by MaxAkbar** [comment]
There is an error with TaxiFarePrediction.Explainability.csproj in which it references ml v1.3. I will fix it as part of this PR.

**Comment by MaxAkbar** [comment]
ML.NET Samples CI (DatabaseIntegration) is failing due to "EF1001: Internal EF Core API usage."
See issue [#12104](https://github.com/aspnet/EntityFrameworkCore/issues/12104) for more details.
updating to 3.1.0-preview2.19525.5 fixes the issue.

**Comment by MaxAkbar** [comment]
After looking at the pipeline looks like it's failing because the build is from .NET Core 2.2 but the project is .NET Core 3.0.

**Comment by MaxAkbar** [comment]
Hello @CESARDELATORRE, let me know if there any changes you would like me to make, thank you?

**Comment by CESARDELATORRE** [comment]
Adding @briacht and @gvashishtha since I just moved to a different team and I won't be able to monitor/drive this repo any longer.
Thanks,

**Pull request closed without merging**
